### ISSUE TITLE
Update tests for upstream changes 

### ISSUE THREAD

**Issue by rabbah** [remore/openwhisk-runtime-ruby#3]
I made several changes upstream for the common runtime test suite: https://github.com/apache/incubator-openwhisk/pull/3840/files#diff-e45924e9432af5ef66840c28bd1ee753

This requires changes to match in this runtime.

**Comment by remore** [comment]
Looks like a little bit bigger issue than others. Give me a while to walkthrough the change had been done in that PR.

**Comment by rabbah** [comment]
yes - i can send a PR once this is in apache if you don't get to it.

**Comment by remore** [comment]
Some of the changes had been supported and now all the tests has passed with Travis CI with this test code:
https://github.com/remore/openwhisk-runtime-ruby/blob/master/tests/src/test/scala/actionContainers/Ruby25ActionContainerTests.scala

Would it be okay for me to send PR to https://github.com/apache/incubator-openwhisk-runtime-ruby repo anyways and start modification (if needed) in apache? @rabbah

**Comment by rabbah** [comment]
excellent - the repo is ready for your first pr.
